In [0]:
import pandas as pd

In [25]:
df = pd.read_csv('FinalData_Avi_Kasliwal.csv')
df.head()

   Unnamed: 0  Player_ID   Player Name  ...  2018  2019  Total Runs
0           0       2601  Aamer Hameed  ...   0.0   0.0         0.0
1           1       2602   Aamer Hanif  ...   0.0   0.0        89.0
2           2       1068   Aamer Malik  ...   0.0   0.0       556.0
3           3       4480   Aamer Yamin  ...  32.0   0.0        95.0
4           4       1259   Aamir Nazir  ...   0.0   0.0        13.0

[5 rows x 55 columns]

In [26]:
names = df['Player Name']
names[: 5]

0    Aamer Hameed
1     Aamer Hanif
2     Aamer Malik
3     Aamer Yamin
4     Aamir Nazir
Name: Player Name, dtype: object

In [28]:
names[0:15]

0     Aamer Hameed
1      Aamer Hanif
2      Aamer Malik
3      Aamer Yamin
4      Aamir Nazir
5     Aamir Sohail
6      Aaqib Javed
7     Aarif Sheikh
8       Aaron. V R
9         Ababu. J
10     Abbott. K J
11     Abbott. S A
12    Abdul Jabbar
13     Abdul Qadir
14    Abdul Razzaq
Name: Player Name, dtype: object

In [0]:
df.drop('Unnamed: 0', axis = 1, inplace = True)

In [30]:
df.head(15)

    Player_ID   Player Name Player_country  1970  ...  2017  2018  2019  Total Runs
0        2601  Aamer Hameed       Pakistan   0.0  ...   0.0   0.0   0.0         0.0
1        2602   Aamer Hanif       Pakistan   0.0  ...   0.0   0.0   0.0        89.0
2        1068   Aamer Malik       Pakistan   0.0  ...   0.0   0.0   0.0       556.0
3        4480   Aamer Yamin       Pakistan   0.0  ...   0.0  32.0   0.0        95.0
4        1259   Aamir Nazir       Pakistan   0.0  ...   0.0   0.0   0.0        13.0
5        1653  Aamir Sohail       Pakistan   0.0  ...   0.0   0.0   0.0      4780.0
6         869   Aaqib Javed       Pakistan   0.0  ...   0.0   0.0   0.0       267.0
7        4808  Aarif Sheikh          Nepal   0.0  ...   0.0  19.0  75.0        19.0
8        3916    Aaron. V R          India   0.0  ...   0.0   0.0   0.0         8.0
9        2603      Ababu. J          Kenya   0.0  ...   0.0   0.0   0.0        29.0
10       4002   Abbott. K J    SouthAfrica   0.0  ...   0.0   0.0   0.0        76.0
11       4331   Abbott. S A      Australia   0.0  ...   0.0   0.0   0.0         3.0
12       3503  Abdul Jabbar         Canada   0.0  ...   0.0   0.0   0.0        59.0
13       1408   Abdul Qadir       Pakistan   0.0  ...   0.0   0.0   0.0       641.0
14       2191  Abdul Razzaq       Pakistan   0.0  ...   0.0   0.0   0.0      5080.0

[15 rows x 54 columns]

In [31]:
df.iloc[:, 3: 53] = df.iloc[:, 3: 53].cumsum(axis = 1)
df.head()

   Player_ID   Player Name Player_country  ...   2018   2019  Total Runs
0       2601  Aamer Hameed       Pakistan  ...    0.0    0.0         0.0
1       2602   Aamer Hanif       Pakistan  ...   89.0   89.0        89.0
2       1068   Aamer Malik       Pakistan  ...  556.0  556.0       556.0
3       4480   Aamer Yamin       Pakistan  ...   95.0   95.0        95.0
4       1259   Aamir Nazir       Pakistan  ...   13.0   13.0        13.0

[5 rows x 54 columns]

In [0]:
df.drop('Player_ID', axis = 1, inplace = True)

In [33]:
df.head()

    Player Name Player_country  1970  1971  ...   2017   2018   2019  Total Runs
0  Aamer Hameed       Pakistan   0.0   0.0  ...    0.0    0.0    0.0         0.0
1   Aamer Hanif       Pakistan   0.0   0.0  ...   89.0   89.0   89.0        89.0
2   Aamer Malik       Pakistan   0.0   0.0  ...  556.0  556.0  556.0       556.0
3   Aamer Yamin       Pakistan   0.0   0.0  ...   63.0   95.0   95.0        95.0
4   Aamir Nazir       Pakistan   0.0   0.0  ...   13.0   13.0   13.0        13.0

[5 rows x 53 columns]

In [0]:
df.to_csv('FinalData_Cum_Avi_kasliwal.csv')